### ISSUE TITLE
Reference PDF should be removed, or excluded from the Cargo package

### ISSUE THREAD

**Issue by chris-morgan** [jneem/lufs#1]
The package on crates.io is currently being bloated by the 1MB reference PDF which isn’t appropriate there. It should at the least be [excluded from the Cargo package](https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields).

But further, reference/R-REC-BS.1770-4-201510-I!!PDF-E.pdf says:

> © ITU 2017
>
> All rights reserved. No part of this publication may be reproduced, by any means whatsoever, without written permission of ITU.

… so I presume that the PDF should be removed from the repository outright. Leave a link to https://www.itu.int/dms_pubrec/itu-r/rec/bs/R-REC-BS.1770-4-201510-I!!PDF-E.pdf instead.

**Comment by jneem** [comment]
Thanks! I've removed it (and yanked 0.1.0 so as to minimize copyright violations).
